Add a new system for rating HW on its learning goals
Ada-Developers-Academy/pedagogy pull request #14
Opened 2018-07-09 23:28 UTC by tildeee

**I generally just... made stuff up**, but I figured it was easier to write something down and talk about it, so let me know what you think.

Would you be willing to add some combination of [R], [S], or [N] on each reading assignment or live code viewing?

2018-07-16 21:23 UTC, droberts-sea requested changes

2018-07-16 21:23 UTC, droberts-ada commented on hw-learning-goal-label-key.md
> +```
Might be more readable to have the rating before the link

2018-07-16 21:23 UTC, droberts-ada commented on hw-learning-goal-label-key.md
> +
These are the ones we consider to be mandatory, right? Can we make that explicit?

2018-07-16 21:23 UTC, droberts-ada commented on hw-learning-goal-label-key.md
> +
>These are the materials we consider to be the most important to our curriculum. If you read nothing else, read the [N]s.

2018-07-17 22:51 UTC, CheezItMan approved these changes
I pretty much agree with Dan's comments, otherwise looks good.

2018-07-19 20:44 UTC, tildeee commented
@droberts-ada just pushed an update re: your suggestions!

2018-07-20 17:25 UTC, droberts-sea approved these changes

2018-07-20 17:25 UTC, merged